inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - "smoke/**/*"
    - "sample/**/*"
    - ".gem_rbs_collection/**/*"
    - "lib/steep/parser.rb"
    - "coverage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Max: 20

Metrics/ClassLength:
  Enabled: true
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Max: 400

Metrics/ModuleLength:
  Enabled: true
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Max: 400
